import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mi Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {/* Header global */}
          <header className="w-full bg-white shadow-md p-4 flex items-center ">
            <Link href="/" className="text-black font-bold text-lg hover:text-gray-700">
              ← Inicio Mercado Cafetero.
            </Link>
          </header>

          {/* Contenido de la página */}
          <main className="mt-4 min-h-screen">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
